import { VerticalBox } from "std-widgets.slint";

export component ImageWindow inherits Window {
    in property <image> source;
    in property <float> image-opacity: 1.0;
    in property <int> image-width: 800;
    in property <int> image-height: 600;

    title: "goon.ai";
    no-frame: true;
    width: root.image-width * 1px;
    height: root.image-height * 1px;
    background: transparent;

    Rectangle {
        width: 100%;
        height: 100%;
        background: transparent;

        Image {
            width: 100%;
            height: 100%;
            source: root.source;
            opacity: root.image-opacity;
            image-fit: contain;
        }
    }
}
