// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioOptions = { tags: Array<string> | null, loop: boolean | null, volume: number | null, };
