// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { Size } from "./Size";

/**
 * Options for displaying an image
 */
export type ImageOptions = {
/**
 * Tags to filter the images by
 */
tags: Array<string> | null,
/**
 * Duration to display the image in seconds
 */
duration: bigint | null, opacity: number | null, position: Position | null, size: Size | null, alwaysOnTop: boolean | null, clickThrough: boolean | null, decorations: boolean | null, };
