// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { Size } from "./Size";

export type PromptOptions = { text: string, fontSize: number | null, color: [number, number, number, number] | null, background: [number, number, number, number] | null, padding: number | null, maxWidth: number | null, alignment: string | null, duration: number | null, opacity: number | null, position: Position | null, size: Size | null, alwaysOnTop: boolean | null, clickThrough: boolean | null, decorations: boolean | null, };
