// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageOptions } from "./ImageOptions";

export type PromptOptions = { text: string, image: ImageOptions | null, };
